language: python
branches:
  only:
  - source
install:
- pip install -r requirements.txt
before_script:
- pelican-themes -i ./theme/twenty
- pelican-themes -l
- ls ./theme
script:
- make publish github
env:
  global:
    secure: rcF7e/u760r4MRBMvl9k9dnuu1UFc8yh/VwFSUD13taf5jvbfE1LiIYLahaUa4kKcSa8+BHIfKZZcm0rVyVTUt4PyXSBoNUl+ShM3Twro9ya99gCUDBAtCzBm/TAVHMDVFeWJ/tX39y00EjszC5MWvf4ZllvnM8iVw+IJHVhmK5LzJj24x4d0QwyAGdcOJQ9TLGeqCR2pAxBllh25iQFfc0mocQBvuvnjI/OuUx3/LBUJXBFCEOgLHylJPGTK5MZIqbpZr4klb7yDwL4wParBX7X9hZF3bOEVldsCx24SkywF+DZjyxqbZXt8PGSIC2fQ/QuBu+dd0R6Ty0BBNMXwCANk1lN4DTZ3QmRAvpM68QTBlzJH6198dz8pO4JpfHrGU5QPwwPssyRZE8hEx30K6exbPNqIiv5CN/MWBXHjTtUKeYzsadAGAKtxFN6NrEFxRX9HGl99SnAjxJ1xGnsSU+veeGyXBcZ1DCEvJd0yz8oF8ro2SgGWbzKpnNPod/orbIidL4ycz/Hv5QKr8Xh7M5mYVHHDsSQIjTj93XCTGyDfe2HjQm9q8TdRD7fcppwikCYpF+RtU7wsl8ilQJh3+zjgALEzxvj9AmL93vuNMXk2kDUMC7XAbx+HockOHoJe1B8pdmjdKqKr68qESkWOo/unu7oYzYqruPt//GGb4I=
